//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Candidate()
        {
            this.Constraints = new HashSet<Constraint>();
            this.MosdotToCandidates = new HashSet<MosdotToCandidate>();
            this.ProposalInProcesses = new HashSet<ProposalInProcess>();
            this.ProposalInProcesses1 = new HashSet<ProposalInProcess>();
        }
    
        public int codeCandidates { get; set; }
        public string FNameCandidates { get; set; }
        public string LNameCandidates { get; set; }
        public bool maleORfemale { get; set; }
        public System.DateTime dateOFbirth { get; set; }
        public int heightCandidates { get; set; }
        public string photoLink { get; set; }
        public string currentNow { get; set; }
        public string occupationAfter { get; set; }
        public Nullable<bool> wigORhandkerchief { get; set; }
        public string addressCandidates { get; set; }
        public string nameFather { get; set; }
        public string nameMother { get; set; }
        public int AdaFather { get; set; }
        public int AdaMother { get; set; }
        public string occupationFather { get; set; }
        public string occupationMother { get; set; }
        public string familyStatus { get; set; }
        public Nullable<int> numberOFchildren { get; set; }
        public Nullable<int> numberOFmarried { get; set; }
        public string VonTOcontact1 { get; set; }
        public string VonTOcontact2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Constraint> Constraints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MosdotToCandidate> MosdotToCandidates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalInProcess> ProposalInProcesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProposalInProcess> ProposalInProcesses1 { get; set; }
        public virtual community community { get; set; }
        public virtual community community1 { get; set; }
    }
}
