//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class The_MatchmakerEntities : DbContext
    {
        public The_MatchmakerEntities()
            : base("name=The_MatchmakerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Candidate> Candidates { get; set; }
        public virtual DbSet<community> communities { get; set; }
        public virtual DbSet<Constraint> Constraints { get; set; }
        public virtual DbSet<ListOfMosdot> ListOfMosdots { get; set; }
        public virtual DbSet<MosdotToCandidate> MosdotToCandidates { get; set; }
        public virtual DbSet<ProposalInProcess> ProposalInProcesses { get; set; }
        public virtual DbSet<StepsOfProposal> StepsOfProposals { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TypesOfStep> TypesOfSteps { get; set; }
        public virtual DbSet<Shadchnit> Shadchnits { get; set; }
    }
}
