//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalInProcess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProposalInProcess()
        {
            this.StepsOfProposals = new HashSet<StepsOfProposal>();
        }
    
        public int codeP { get; set; }
        public int codeBT { get; set; }
        public int codeBN { get; set; }
        public Nullable<System.DateTime> dateP { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Candidate Candidate1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StepsOfProposal> StepsOfProposals { get; set; }
    }
}
